default: &default
  adapter: mysql2
  encoding: utf8
  username: imap_api
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: imap_api

test:
  <<: *default
  database: imap_api_test

production:
  <<: *default
  database: imap_api
