# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6330563f8cbfc473a9c838260fdff66e4bbbd95231e9d91851b41374eb08eec40f60a3434237a60c421042b72ab22867741018eeedc99869eed81e0b0296d59d

test:
  secret_key_base: 8496f8467edd7678fc77bed15205a60a0b36d2e68cce2370db38242fbb5066f412f943534b82c6b48fa67e42e14cf83a69358a093e74ca1ceab9806a841a49e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
